package com.tether.app.client

import java.security.UnrecoverableKeyException
import javax.crypto.AEADBadTagException
import javax.crypto.BadPaddingException
import javax.crypto.Cipher
import javax.crypto.IllegalBlockSizeException
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Seals a credential (the `tether_session` cookie value or a `tthr_` device
 * token) for storage at rest. [aad] binds a blob to the slot it was written for,
 * so a ciphertext copied from one slot into another does not decrypt.
 *
 * Both calls throw [CredentialCipherException] and never anything that carries
 * the plaintext. Callers treat a failed [open] as "no credential" (logged out).
 */
interface CredentialCipher {
    fun seal(plaintext: ByteArray, aad: ByteArray): ByteArray

    fun open(blob: ByteArray, aad: ByteArray): ByteArray

    /**
     * Forget the key (e.g. after it was invalidated). The next [seal] creates a
     * fresh one; every blob sealed under the old key is unrecoverable.
     */
    fun destroyKey()
}

/**
 * Three kinds of failure, which the store treats differently:
 * - [keyUnusable]: the key is missing, permanently invalidated
 *   (KeyPermanentlyInvalidatedException) or unrecoverable. Every blob sealed
 *   under it is dead; the store destroys the key and deletes the blobs.
 * - [transient]: the Keystore could not be used right now (KeyStoreException,
 *   ProviderException, a daemon hiccup). The key and the blob are LEFT alone and
 *   the credential reads as "unavailable this time"; the next use retries.
 * - neither: this blob is bad (corrupt, truncated, wrong slot/origin) and is deleted.
 * The message never contains credential material.
 */
class CredentialCipherException(
    message: String,
    val keyUnusable: Boolean = false,
    val transient: Boolean = false,
) : Exception(message)

/** Where the AES key lives. The production source is the Android Keystore. */
interface CredentialKeySource {
    /** The existing key, or null when there is none (never creates one). */
    fun existingKey(): SecretKey?

    /** The existing key, or a freshly generated one. */
    fun getOrCreateKey(): SecretKey

    fun destroyKey()
}

/**
 * AES-256-GCM with a 128-bit tag. Blob layout: `[version=1][12-byte IV][ciphertext || tag]`.
 *
 * The IV is generated by the provider at every [seal] (Android Keystore keys
 * enforce randomized encryption, so the caller never chooses one) and stored in
 * front of the ciphertext. A 96-bit random IV per message is safe for the tiny
 * number of messages one key ever seals here (a handful per login).
 *
 * The framing is identical for every [CredentialKeySource], which is what makes
 * it testable on the JVM with a software key while production uses a
 * non-exportable Keystore key.
 */
class AesGcmCredentialCipher(private val keys: CredentialKeySource) : CredentialCipher {

    override fun seal(plaintext: ByteArray, aad: ByteArray): ByteArray {
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, keys.getOrCreateKey())
            cipher.updateAAD(aad)
            val iv = cipher.iv
            if (iv == null || iv.size != IV_BYTES) throw CredentialCipherException("unexpected IV length", transient = true)
            val sealed = cipher.doFinal(plaintext)
            return byteArrayOf(VERSION) + iv + sealed
        } catch (e: CredentialCipherException) {
            throw e
        } catch (e: Exception) {
            throw classify("seal", e)
        }
    }

    override fun open(blob: ByteArray, aad: ByteArray): ByteArray {
        if (blob.size < 1 + IV_BYTES + TAG_BYTES) throw CredentialCipherException("blob too short")
        if (blob[0] != VERSION) throw CredentialCipherException("unknown blob version")
        val key = try {
            keys.existingKey()
        } catch (e: Exception) {
            throw classify("key fetch", e)
        } ?: throw CredentialCipherException("no key", keyUnusable = true)
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(TAG_BYTES * 8, blob, 1, IV_BYTES))
            cipher.updateAAD(aad)
            return cipher.doFinal(blob, 1 + IV_BYTES, blob.size - 1 - IV_BYTES)
        } catch (e: Exception) {
            throw classify("open", e)
        }
    }

    override fun destroyKey() {
        try {
            keys.destroyKey()
        } catch (_: Exception) {
            // Nothing to recover: a key we cannot delete is also one we cannot use.
        }
    }

    /**
     * Only a permanently invalidated or unrecoverable key is "unusable" (and gets
     * destroyed). A bad tag / bad padding is this blob's fault. Everything else —
     * KeyStoreException, ProviderException, a generic InvalidKeyException from a
     * Keystore hiccup — is transient: destroying the key for it would sign the
     * user out over a momentary error.
     */
    private fun classify(what: String, e: Exception): CredentialCipherException {
        val name = e.javaClass.simpleName
        return when {
            isPermanentKeyFailure(e) -> CredentialCipherException("$what: key unusable ($name)", keyUnusable = true)
            e is AEADBadTagException || e is BadPaddingException || e is IllegalBlockSizeException ->
                CredentialCipherException("$what: blob rejected ($name)")
            else -> CredentialCipherException("$what: keystore unavailable ($name)", transient = true)
        }
    }

    private fun isPermanentKeyFailure(e: Throwable): Boolean =
        e is UnrecoverableKeyException ||
            // android.security.keystore.KeyPermanentlyInvalidatedException (matched by
            // name: it is an Android class, and this file is JVM-tested).
            generateSequence<Class<*>>(e.javaClass) { it.superclass }.any { it.name == KEY_PERMANENTLY_INVALIDATED }

    companion object {
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val VERSION: Byte = 1
        const val IV_BYTES = 12
        const val TAG_BYTES = 16
        private const val KEY_PERMANENTLY_INVALIDATED = "android.security.keystore.KeyPermanentlyInvalidatedException"
    }
}
