package com.tether.app.client

import java.security.GeneralSecurityException
import java.security.ProviderException
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Seals a credential (the `tether_session` cookie value or a `tthr_` device
 * token) for storage at rest. [aad] binds a blob to the slot it was written for,
 * so a ciphertext copied from one slot into another does not decrypt.
 *
 * Both calls throw [CredentialCipherException] and never anything that carries
 * the plaintext. Callers treat a failed [open] as "no credential" (logged out).
 */
interface CredentialCipher {
    fun seal(plaintext: ByteArray, aad: ByteArray): ByteArray

    fun open(blob: ByteArray, aad: ByteArray): ByteArray

    /**
     * Forget the key (e.g. after it was invalidated). The next [seal] creates a
     * fresh one; every blob sealed under the old key is unrecoverable.
     */
    fun destroyKey()
}

/**
 * [keyUnusable] = the key itself is gone or permanently invalid, so every blob
 * sealed under it is dead (the store then destroys the key). Otherwise only this
 * blob is bad (corrupt, truncated, wrong slot). The message never contains
 * credential material.
 */
class CredentialCipherException(
    message: String,
    val keyUnusable: Boolean = false,
    cause: Throwable? = null,
) : Exception(message, cause)

/** Where the AES key lives. The production source is the Android Keystore. */
interface CredentialKeySource {
    /** The existing key, or null when there is none (never creates one). */
    fun existingKey(): SecretKey?

    /** The existing key, or a freshly generated one. */
    fun getOrCreateKey(): SecretKey

    fun destroyKey()
}

/**
 * AES-256-GCM with a 128-bit tag. Blob layout: `[version=1][12-byte IV][ciphertext || tag]`.
 *
 * The IV is generated by the provider at every [seal] (Android Keystore keys
 * enforce randomized encryption, so the caller never chooses one) and stored in
 * front of the ciphertext. A 96-bit random IV per message is safe for the tiny
 * number of messages one key ever seals here (a handful per login).
 *
 * The framing is identical for every [CredentialKeySource], which is what makes
 * it testable on the JVM with a software key while production uses a
 * non-exportable Keystore key.
 */
class AesGcmCredentialCipher(private val keys: CredentialKeySource) : CredentialCipher {

    override fun seal(plaintext: ByteArray, aad: ByteArray): ByteArray {
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, keys.getOrCreateKey())
            cipher.updateAAD(aad)
            val iv = cipher.iv
            if (iv == null || iv.size != IV_BYTES) throw CredentialCipherException("unexpected IV length")
            val sealed = cipher.doFinal(plaintext)
            return byteArrayOf(VERSION) + iv + sealed
        } catch (e: CredentialCipherException) {
            throw e
        } catch (e: GeneralSecurityException) {
            throw CredentialCipherException("seal failed: ${e.javaClass.simpleName}", keyUnusable = isKeyFailure(e), cause = null)
        } catch (e: ProviderException) {
            // Keystore daemon / hardware errors surface as ProviderException.
            throw CredentialCipherException("seal failed: ${e.javaClass.simpleName}", keyUnusable = false, cause = null)
        } catch (e: RuntimeException) {
            throw CredentialCipherException("seal failed: ${e.javaClass.simpleName}", keyUnusable = false, cause = null)
        }
    }

    override fun open(blob: ByteArray, aad: ByteArray): ByteArray {
        if (blob.size < 1 + IV_BYTES + TAG_BYTES) throw CredentialCipherException("blob too short")
        if (blob[0] != VERSION) throw CredentialCipherException("unknown blob version")
        val key = try {
            keys.existingKey()
        } catch (e: GeneralSecurityException) {
            throw CredentialCipherException("key unavailable: ${e.javaClass.simpleName}", keyUnusable = true)
        } catch (e: RuntimeException) {
            throw CredentialCipherException("key unavailable: ${e.javaClass.simpleName}", keyUnusable = true)
        } ?: throw CredentialCipherException("no key", keyUnusable = true)
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(TAG_BYTES * 8, blob, 1, IV_BYTES))
            cipher.updateAAD(aad)
            return cipher.doFinal(blob, 1 + IV_BYTES, blob.size - 1 - IV_BYTES)
        } catch (e: GeneralSecurityException) {
            throw CredentialCipherException("open failed: ${e.javaClass.simpleName}", keyUnusable = isKeyFailure(e))
        } catch (e: ProviderException) {
            throw CredentialCipherException("open failed: ${e.javaClass.simpleName}", keyUnusable = false)
        } catch (e: RuntimeException) {
            throw CredentialCipherException("open failed: ${e.javaClass.simpleName}", keyUnusable = false)
        }
    }

    override fun destroyKey() {
        try {
            keys.destroyKey()
        } catch (_: Exception) {
            // Nothing to recover: a key we cannot delete is also one we cannot use.
        }
    }

    /**
     * The key itself is unusable: android.security.keystore.KeyPermanentlyInvalidatedException
     * (a Keystore reset, a lock-screen change on some OEMs) is an
     * InvalidKeyException. A bad tag (corrupt blob, wrong slot) is not.
     */
    private fun isKeyFailure(e: Throwable): Boolean =
        e is java.security.InvalidKeyException || e is java.security.UnrecoverableKeyException

    companion object {
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val VERSION: Byte = 1
        const val IV_BYTES = 12
        const val TAG_BYTES = 16
    }
}
