package com.tether.app.client

import java.security.Provider
import java.security.UnrecoverableKeyException
import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Seals a credential (the `tether_session` cookie value or a `tthr_` device
 * token) for storage at rest. [aad] binds a blob to the slot it was written for,
 * so a ciphertext copied from one slot into another does not decrypt.
 *
 * Both calls throw [CredentialCipherException] and never anything that carries
 * the plaintext. Callers treat a failed [open] as "no credential" (logged out).
 */
interface CredentialCipher {
    fun seal(plaintext: ByteArray, aad: ByteArray): ByteArray

    fun open(blob: ByteArray, aad: ByteArray): ByteArray

    /**
     * Forget the key (e.g. after it was invalidated). The next [seal] creates a
     * fresh one; every blob sealed under the old key is unrecoverable.
     */
    fun destroyKey()
}

/**
 * How a cipher operation failed; the store treats each differently.
 * The message never contains credential material.
 */
enum class CipherFailure {
    /** This blob is bad (corrupt, truncated, wrong slot/origin — a GCM tag mismatch): delete it. */
    BadBlob,

    /** The key is missing or permanently invalidated: destroy it, every blob under it is dead. */
    KeyDead,

    /**
     * The Keystore said "not right now" (a KeyStoreException in the cause chain
     * that is, or may be, transient): keep the key and the blob, read as logged
     * out this time, retry on the next use. Does not count toward rotation.
     */
    Transient,

    /**
     * Unexplained (e.g. a bare IllegalBlockSizeException / InvalidKeyException,
     * which is how Android Keystore surfaces most provider failures): treated as
     * transient, but the store counts consecutive launches that hit it and rotates
     * the key after [DataStoreSettings.SUSPECT_ROTATE_AFTER], so a key that is
     * broken for good does not force a sign-in on every launch forever.
     */
    Suspect,
}

class CredentialCipherException(
    message: String,
    val failure: CipherFailure = CipherFailure.BadBlob,
) : Exception(message) {
    val keyUnusable: Boolean get() = failure == CipherFailure.KeyDead
    val transient: Boolean get() = failure == CipherFailure.Transient || failure == CipherFailure.Suspect
}

/** Where the AES key lives. The production source is the Android Keystore. */
interface CredentialKeySource {
    /** The existing key, or null when there is none (never creates one). */
    fun existingKey(): SecretKey?

    /** The existing key, or a freshly generated one. */
    fun getOrCreateKey(): SecretKey

    fun destroyKey()
}

/**
 * AES-256-GCM with a 128-bit tag. Blob layout: `[version=1][12-byte IV][ciphertext || tag]`.
 *
 * The IV is generated by the provider at every [seal] (Android Keystore keys
 * enforce randomized encryption, so the caller never chooses one) and stored in
 * front of the ciphertext. A 96-bit random IV per message is safe for the tiny
 * number of messages one key ever seals here (a handful per login).
 *
 * The framing is identical for every [CredentialKeySource], which is what makes
 * it testable on the JVM with a software key while production uses a
 * non-exportable Keystore key.
 *
 * Production passes no [provider]: JCA's delayed provider selection hands a Keystore key
 * to the Keystore's own cipher (Conscrypt's AES ciphers take RAW-encoded keys only, and a
 * Keystore key has no encoding). [provider] exists so JVM tests can pin SunJCE or Conscrypt
 * instead of inheriting whichever one a Robolectric sandbox installed first (ta-js0).
 */
class AesGcmCredentialCipher internal constructor(
    private val keys: CredentialKeySource,
    private val provider: Provider?,
) : CredentialCipher {

    constructor(keys: CredentialKeySource) : this(keys, null)

    private fun newCipher(): Cipher =
        if (provider == null) Cipher.getInstance(TRANSFORMATION) else Cipher.getInstance(TRANSFORMATION, provider)

    override fun seal(plaintext: ByteArray, aad: ByteArray): ByteArray {
        try {
            val cipher = newCipher()
            cipher.init(Cipher.ENCRYPT_MODE, keys.getOrCreateKey())
            cipher.updateAAD(aad)
            val iv = cipher.iv
            if (iv == null || iv.size != IV_BYTES) throw CredentialCipherException("unexpected IV length", CipherFailure.Suspect)
            val sealed = cipher.doFinal(plaintext)
            return byteArrayOf(VERSION) + iv + sealed
        } catch (e: CredentialCipherException) {
            throw e
        } catch (e: Exception) {
            throw classifyCipherFailure("seal", e)
        }
    }

    override fun open(blob: ByteArray, aad: ByteArray): ByteArray {
        if (blob.size < 1 + IV_BYTES + TAG_BYTES) throw CredentialCipherException("blob too short")
        if (blob[0] != VERSION) throw CredentialCipherException("unknown blob version")
        val key = try {
            keys.existingKey()
        } catch (e: Exception) {
            throw classifyCipherFailure("key fetch", e)
        } ?: throw CredentialCipherException("no key", CipherFailure.KeyDead)
        try {
            val cipher = newCipher()
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(TAG_BYTES * 8, blob, 1, IV_BYTES))
            cipher.updateAAD(aad)
            return cipher.doFinal(blob, 1 + IV_BYTES, blob.size - 1 - IV_BYTES)
        } catch (e: Exception) {
            throw classifyCipherFailure("open", e)
        }
    }

    override fun destroyKey() {
        try {
            keys.destroyKey()
        } catch (_: Exception) {
            // Nothing to recover: a key we cannot delete is also one we cannot use.
        }
    }

    companion object {
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val VERSION: Byte = 1
        const val IV_BYTES = 12
        const val TAG_BYTES = 16
    }
}

private const val KEY_PERMANENTLY_INVALIDATED = "android.security.keystore.KeyPermanentlyInvalidatedException"

/**
 * Classify a Keystore / JCE failure. Android Keystore maps most provider
 * failures in doFinal to IllegalBlockSizeException and wraps the real cause, so
 * the cause chain decides:
 * 1. KeyPermanentlyInvalidatedException anywhere → [CipherFailure.KeyDead].
 * 1b. A TOP-LEVEL AEADBadTagException → [CipherFailure.BadBlob], whatever its cause: on a
 *    device Keystore throws the tag failure as `AEADBadTagException().initCause(
 *    android.security.KeyStoreException)`, so rule 2 must not see its cause first (security
 *    re-review, T1.4).
 * 2. A KeyStoreException anywhere (java.security's, or android.security's on
 *    API 33+) → [CipherFailure.Transient] — unless it reports
 *    `isTransientFailure() == false`, which makes it [CipherFailure.Suspect].
 *    This includes an UnrecoverableKeyException CAUSED by such an error.
 * 3. A bare UnrecoverableKeyException → [CipherFailure.KeyDead].
 * 4. AEADBadTagException (the GCM tag did not verify) → [CipherFailure.BadBlob]:
 *    the only proof that the blob, not the Keystore, is wrong.
 * 5. Anything else → [CipherFailure.Suspect].
 *
 * Providers (ta-js0). On a device the Keystore cipher throws the tag failure (KM error -30) as
 * AEADBadTagException, and every other operation error as IllegalBlockSizeException or
 * BadPaddingException caused by an android.security.KeyStoreException. A software provider
 * (SunJCE or Conscrypt, in JVM tests) cannot tell "another key" from "a tampered blob": both are
 * a tag mismatch, so both are BadBlob, which drops the blob and keeps the key. The
 * providers differ on a key they cannot use: SunJCE rejects a non-AES algorithm name with
 * InvalidKeyException (rule 5), but Conscrypt ignores the name and uses any 16- or 32-byte
 * RAW key as AES, so the same key surfaces as a tag mismatch (rule 4). Neither case ever
 * destroys the key.
 */
internal fun classifyCipherFailure(what: String, e: Throwable): CredentialCipherException {
    val name = e.javaClass.simpleName
    val chain = generateSequence(e) { it.cause.takeIf { c -> c !== it } }.take(16).toList()
    fun hierarchyNamed(t: Throwable, fqcn: String) =
        generateSequence<Class<*>>(t.javaClass) { it.superclass }.any { it.name == fqcn }
    val failure = when {
        chain.any { hierarchyNamed(it, KEY_PERMANENTLY_INVALIDATED) } -> CipherFailure.KeyDead
        e is AEADBadTagException -> CipherFailure.BadBlob
        chain.any { isKeyStoreException(it) } -> {
            val reportsPermanent = chain.filter { isKeyStoreException(it) }.any { transientFlag(it) == false }
            if (reportsPermanent) CipherFailure.Suspect else CipherFailure.Transient
        }
        chain.any { it is UnrecoverableKeyException } -> CipherFailure.KeyDead
        chain.any { it is AEADBadTagException } -> CipherFailure.BadBlob
        else -> CipherFailure.Suspect
    }
    return CredentialCipherException("$what failed ($name): $failure", failure)
}

/** java.security.KeyStoreException, android.security.KeyStoreException (API 33+), or a lookalike. */
private fun isKeyStoreException(t: Throwable): Boolean =
    t is java.security.KeyStoreException ||
        generateSequence<Class<*>>(t.javaClass) { it.superclass }.any { it.simpleName == "KeyStoreException" }

/** `isTransientFailure()` when the exception has it (android.security.KeyStoreException, API 33+); else null. */
private fun transientFlag(t: Throwable): Boolean? = try {
    t.javaClass.getMethod("isTransientFailure").invoke(t) as? Boolean
} catch (_: ReflectiveOperationException) {
    null
} catch (_: RuntimeException) {
    null
}
